const booksData = [
  {
    "id": 1,
    "title": "A Brief History of Time",
    "category": "Science",
    "coverImage": "http://books.google.com/books/content?id=1Q6nDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "A landmark volume in science writing by one of the great minds of our time, Stephen Hawking's book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends?",
    "pageCount": 212,
    "authors": "Stephen Hawking",
    "tags": ["Science", "Physics", "Cosmology"],
    "price": "189.99",
    "averageRating": 4.2,
    "ratingsCount": 4521,
    "bestSelling":true
  },
  {
    "id": 2,
    "title": "The Selfish Gene",
    "category": "Science",
    "coverImage": "http://books.google.com/books/content?id=ekonDAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Richard Dawkins' brilliant reformulation of the theory of natural selection has the rare distinction of having provoked as much excitement and interest outside the scientific community as within it. His theories have helped change the whole nature of the study of social biology, and have forced thousands of readers to rethink their beliefs about life.",
    "pageCount": 360,
    "authors": "Richard Dawkins",
    "tags": ["Science", "Biology", "Evolution"],
    "price": "199.99",
    "averageRating": 4.3,
    "ratingsCount": 3845,
    "bestSelling":true
  },
  {
    "id": 3,
    "title": "Sapiens: A Brief History of Humankind",
    "category": "Science",
    "coverImage": "http://books.google.com/books/content?id=FmyBAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be human.",
    "pageCount": 443,
    "authors": "Yuval Noah Harari",
    "tags": ["Science", "History", "Anthropology"],
    "price": "229.99",
    "averageRating": 4.5,
    "ratingsCount": 8932,
    "trending":true,
  },
  {
    "id": 4,
    "title": "The Structure of Scientific Revolutions",
    "category": "Science",
    "coverImage": "http://books.google.com/books/content?id=3eP5Y_OOuzwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "A good book may have the power to change the way we see the world, but a great book actually becomes part of our daily consciousness, pervading our thinking to the point that we take it for granted. This book has had enormous impact on the way we think about science.",
    "pageCount": 212,
    "authors": "Thomas S. Kuhn",
    "tags": ["Science", "Philosophy", "History"],
    "price": "179.99",
    "averageRating": 4.1,
    "ratingsCount": 2156
  },
  {
    "id": 5,
    "title": "The Origin of Species",
    "category": "Science",
    "coverImage": "http://books.google.com/books/content?id=tMu1EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Charles Darwin's groundbreaking work of evolutionary biology that introduced the scientific theory of evolution through natural selection. This revolutionary book changed the way we understand life on Earth.",
    "pageCount": 502,
    "authors": "Charles Darwin",
    "tags": ["Science", "Biology", "Classics"],
    "price": "149.99",
    "averageRating": 4.4,
    "ratingsCount": 5621
  },
  {
    "id": 6,
    "title": "Cosmos",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=EIqoiww1r9sC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Carl Sagan's Cosmos is one of the bestselling science books of all time. In clear-eyed prose, Sagan reveals a jewel-like blue world inhabited by a life form that is just beginning to discover its own identity and to venture into the vast ocean of space.",
    "pageCount": 384,
    "authors": "Carl Sagan",
    "tags": ["Astronomy", "Science", "Space"],
    "price": "209.99",
    "averageRating": 4.6,
    "ratingsCount": 6743,
    "bestSelling":true
  },
  {
    "id": 7,
    "title": "Astrophysics for People in a Hurry",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=hx5DDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "What is the nature of space and time? How do we fit within the universe? How does the universe fit within us? There's no better guide through these mind-expanding questions than acclaimed astrophysicist and best-selling author Neil deGrasse Tyson.",
    "pageCount": 224,
    "authors": "Neil deGrasse Tyson",
    "tags": ["Astronomy", "Physics", "Science"],
    "price": "169.99",
    "averageRating": 4.3,
    "ratingsCount": 4521
  },
  {
    "id": 8,
    "title": "The Elegant Universe",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=MNHzwnEYi40C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Brian Greene, one of the world's leading string theorists, peels away layers of mystery to reveal a universe that consists of eleven dimensions. A new edition of the New York Times bestseller.",
    "pageCount": 448,
    "authors": "Brian Greene",
    "tags": ["Astronomy", "Physics", "Cosmology"],
    "price": "219.99",
    "averageRating": 4.2,
    "ratingsCount": 3214,
    "trending":true,
    "bestSelling":true
  },
  {
    "id": 9,
    "title": "The Universe in a Nutshell",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=0CO2iwfzRJkC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Stephen Hawking's phenomenal, multimillion-copy bestseller, A Brief History of Time, introduced the ideas of this brilliant theoretical physicist to readers all over the world. Now, in a major publishing event, Hawking returns with a lavishly illustrated sequel.",
    "pageCount": 216,
    "authors": "Stephen Hawking",
    "tags": ["Astronomy", "Physics", "Science"],
    "price": "199.99",
    "averageRating": 4.4,
    "ratingsCount": 2987
  },
  {
    "id": 10,
    "title": "A Brief History of Black Holes",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=YT0KEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Black holes are a constant source of fascination to many due to their mysterious nature. This book provides an accessible introduction to these cosmic phenomena, exploring the latest discoveries in astronomy.",
    "pageCount": 256,
    "authors": "Becky Smethurst",
    "tags": ["Astronomy", "Space", "Physics"],
    "price": "159.99",
    "averageRating": 4.1,
    "ratingsCount": 1823
  },
  {
    "id": 50,
    "title": "Quantum Entanglement",
    "category": "Astronomy",
    "coverImage": "http://books.google.com/books/content?id=52PMDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "An exploration of quantum entanglement and the ways in which it contradicts our everyday assumptions about the ultimate nature of reality. Quantum entanglement—called by Einstein 'spooky action at a distance'—rejects common assumptions, offering impeccable reasoning and irrefutable evidence of the opposite.",
    "pageCount": 184,
    "authors": "Jed Brody",
    "tags": ["Physics", "Quantum Mechanics", "Science"],
    "price": "149.99",
    "averageRating": 4.0,
    "ratingsCount": 245,
    "topBookOfTheWeek":true,

},
  {
    "id": 11,
    "title": "1984",
    "category": "Fiction",
    "coverImage": "http://books.google.com/books/content?id=kotPYEqx7kMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world.",
    "pageCount": 328,
    "authors": "George Orwell",
    "tags": ["Fiction", "Dystopian", "Classics"],
    "price": "139.99",
    "averageRating": 4.6,
    "ratingsCount": 12543
  },
  {
    "id": 12,
    "title": "To Kill a Mockingbird",
    "category": "Fiction",
    "coverImage": "http://books.google.com/books/content?id=PGR2AwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Harper Lee's Pulitzer Prize-winning masterwork of honor and injustice in the deep South—and the heroism of one man in the face of blind and violent hatred. One of the best-loved stories of all time.",
    "pageCount": 324,
    "authors": "Harper Lee",
    "tags": ["Fiction", "Classics", "Drama"],
    "price": "149.99",
    "averageRating": 4.7,
    "ratingsCount": 15234
  },
  {
    "id": 13,
    "title": "Pride and Prejudice",
    "category": "Fiction",
    "coverImage": "http://books.google.com/books/content?id=s1gVAAAAYAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Jane Austen's beloved classic opens with one of the most famous lines in literature: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.'",
    "pageCount": 432,
    "authors": "Jane Austen",
    "tags": ["Fiction", "Romance", "Classics"],
    "price": "129.99",
    "averageRating": 4.5,
    "ratingsCount": 18765,
    "bestSelling":true
  },
  {
    "id": 14,
    "title": "The Great Gatsby",
    "category": "Fiction",
    "coverImage": "http://books.google.com/books/content?id=iXn5U2IzVH0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "F. Scott Fitzgerald's classic American novel of the Roaring Twenties is beloved by generations of readers and stands as his crowning work. This classic novel of the Jazz Age has been acclaimed by generations of readers.",
    "pageCount": 180,
    "authors": "F. Scott Fitzgerald",
    "tags": ["Fiction", "Classics", "Drama"],
    "price": "119.99",
    "averageRating": 4.3,
    "ratingsCount": 9876,
    "trending":true,
  },
  {
    "id": 15,
    "title": "The Catcher in the Rye",
    "category": "Fiction",
    "coverImage": "http://books.google.com/books/content?id=mZunDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days.",
    "pageCount": 277,
    "authors": "J.D. Salinger",
    "tags": ["Fiction", "Coming of Age", "Classics"],
    "price": "139.99",
    "averageRating": 4.0,
    "ratingsCount": 11234,
    "topBookOfTheWeek":true,
  },
  {
    "id": 16,
    "title": "Where the Wild Things Are",
    "category": "Kids",
    "coverImage": "http://books.google.com/books/content?id=GVWtPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Max, a wild and naughty boy, is sent to bed without his supper by his exhausted mother. In his room, he imagines sailing far away to a land of Wild Things. Instead of eating him, the Wild Things make Max their king.",
    "pageCount": 48,
    "authors": "Maurice Sendak",
    "tags": ["Kids", "Picture Book", "Fantasy"],
    "price": "89.99",
    "averageRating": 4.8,
    "ratingsCount": 6543
  },
  {
    "id": 17,
    "title": "The Very Hungry Caterpillar",
    "category": "Kids",
    "coverImage": "http://books.google.com/books/content?id=zMt1DQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "The classic story of the caterpillar who ate through one apple on Monday, two pears on Tuesday... and still was hungry. Strikingly bold graphics in Eric Carle's trademark collage style.",
    "pageCount": 26,
    "authors": "Eric Carle",
    "tags": ["Kids", "Picture Book", "Educational"],
    "price": "79.99",
    "averageRating": 4.9,
    "ratingsCount": 8932
  },
  {
    "id": 18,
    "title": "Charlotte's Web",
    "category": "Kids",
    "coverImage": "http://books.google.com/books/content?id=UouqnNklemkC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "This beloved book by E. B. White, author of Stuart Little and The Trumpet of the Swan, is a classic of children's literature. It's the story of a little girl named Fern who loved a little pig named Wilbur—and of Wilbur's dear friend Charlotte A. Cavatica, a beautiful large grey spider.",
    "pageCount": 192,
    "authors": "E.B. White",
    "tags": ["Kids", "Fiction", "Animals"],
    "price": "99.99",
    "averageRating": 4.7,
    "ratingsCount": 7654,
    "topBookOfTheWeek":true,
  },
  {
    "id": 19,
    "title": "The Cat in the Hat",
    "category": "Kids",
    "coverImage": "http://books.google.com/books/content?id=XPpZAAAAYAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Poor Dick and Sally. It's cold and wet and they're stuck in the house with nothing to do... until a giant cat in a hat shows up, transforming the dull day into a madcap adventure.",
    "pageCount": 61,
    "authors": "Dr. Seuss",
    "tags": ["Kids", "Picture Book", "Humor"],
    "price": "69.99",
    "averageRating": 4.6,
    "ratingsCount": 5432,
    "trending":true,
  },
  {
    "id": 20,
    "title": "Goodnight Moon",
    "category": "Kids",
    "coverImage": "http://books.google.com/books/content?id=Ms5stwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "In a great green room, tucked away in bed, is a little bunny. 'Goodnight room, goodnight moon.' And to all the familiar things in the softly lit room—to the picture of the three little bears sitting on chairs, to the clocks and his socks, to the mittens and the kittens.",
    "pageCount": 32,
    "authors": "Margaret Wise Brown",
    "tags": ["Kids", "Bedtime", "Picture Book"],
    "price": "79.99",
    "averageRating": 4.8,
    "ratingsCount": 9123
  },
  {
    "id": 21,
    "title": "The Hobbit",
    "category": "Adventure",
    "coverImage": "http://books.google.com/books/content?id=pD6arNyKyi8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.",
    "pageCount": 366,
    "authors": "J.R.R. Tolkien",
    "tags": ["Adventure", "Fantasy", "Classics"],
    "price": "169.99",
    "averageRating": 4.7,
    "ratingsCount": 14532
  },
  {
    "id": 22,
    "title": "Treasure Island",
    "category": "Adventure",
    "coverImage": "http://books.google.com/books/content?id=Bpo9AQAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Robert Louis Stevenson's classic tale of pirates, treasure, and adventure on the high seas. Young Jim Hawkins finds himself owner of a map to Treasure Island, where the fabled pirate booty is buried.",
    "pageCount": 292,
    "authors": "Robert Louis Stevenson",
    "tags": ["Adventure", "Classics", "Pirates"],
    "price": "119.99",
    "averageRating": 4.4,
    "ratingsCount": 8765
  },
  {
    "id": 23,
    "title": "Into the Wild",
    "category": "Adventure",
    "coverImage": "http://books.google.com/books/content?id=m9BiDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "In April 1992 a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. His name was Christopher Johnson McCandless. He had given away his savings, abandoned his car and most of his possessions, burned all the cash in his wallet.",
    "pageCount": 207,
    "authors": "Jon Krakauer",
    "tags": ["Adventure", "Biography", "Non-fiction"],
    "price": "159.99",
    "averageRating": 4.3,
    "ratingsCount": 6543,
    "topBookOfTheWeek":true,
  },
  {
    "id": 24,
    "title": "The Call of the Wild",
    "category": "Adventure",
    "coverImage": "http://books.google.com/books/content?id=j6L-qusnoTUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Jack London's classic adventure novel about Buck, a domesticated dog who is stolen and sold as a sled dog in the Alaskan Klondike during the 1890s Gold Rush. Buck must adapt to survive the harsh wilderness.",
    "pageCount": 232,
    "authors": "Jack London",
    "tags": ["Adventure", "Classics", "Animals"],
    "price": "109.99",
    "averageRating": 4.5,
    "ratingsCount": 7234
  },
  {
    "id": 25,
    "title": "Life of Pi",
    "category": "Adventure",
    "coverImage": "http://books.google.com/books/content?id=O8ZaEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "After the tragic sinking of a cargo ship, one solitary lifeboat remains bobbing on the wild, blue Pacific. The only survivors from the wreck are a sixteen-year-old boy named Pi, a hyena, a zebra with a broken leg, a female orang-utan - and a 450-pound Royal Bengal tiger.",
    "pageCount": 460,
    "authors": "Yann Martel",
    "tags": ["Adventure", "Fiction", "Survival"],
    "price": "179.99",
    "averageRating": 4.2,
    "ratingsCount": 9876,
    "bestSelling":true
  },
  {
    "id": 26,
    "title": "Dune",
    "category": "Science Fiction",
    "coverImage": "http://books.google.com/books/content?id=B1hSG45JCX4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange, a drug capable of extending life and enhancing consciousness.",
    "pageCount": 688,
    "authors": "Frank Herbert",
    "tags": ["Science Fiction", "Adventure", "Classics"],
    "price": "219.99",
    "averageRating": 4.6,
    "ratingsCount": 11234
  },
  {
    "id": 27,
    "title": "Foundation",
    "category": "Science Fiction",
    "coverImage": "http://books.google.com/books/content?id=IwywDY4P6gsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Isaac Asimov's Foundation series is considered one of the greatest works of science fiction ever. For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future.",
    "pageCount": 296,
    "authors": "Isaac Asimov",
    "tags": ["Science Fiction", "Space", "Classics"],
    "price": "189.99",
    "averageRating": 4.5,
    "ratingsCount": 8932,
    "bestSelling":true
  },
  {
    "id": 28,
    "title": "Neuromancer",
    "category": "Science Fiction",
    "coverImage": "http://books.google.com/books/content?id=z9BaAAAAYAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "The Matrix is a world within the world, a global consensus-hallucination, the representation of every byte of data in cyberspace. Case had been the sharpest data-thief in the business, until vengeful former employers crippled his nervous system.",
    "pageCount": 271,
    "authors": "William Gibson",
    "tags": ["Science Fiction", "Cyberpunk", "Dystopian"],
    "price": "169.99",
    "averageRating": 4.1,
    "ratingsCount": 6543
  },
  {
    "id": 29,
    "title": "The Martian",
    "category": "Science Fiction",
    "coverImage": "http://books.google.com/books/content?id=MQeHAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone.",
    "pageCount": 369,
    "authors": "Andy Weir",
    "tags": ["Science Fiction", "Space", "Survival"],
    "price": "199.99",
    "averageRating": 4.7,
    "ratingsCount": 15234
  },
  {
  "id": 30,
  "title": "The Hitchhiker's Guide to the Galaxy",
  "category": "Science Fiction",
  "coverImage": "http://books.google.com/books/content?id=W-xMPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Seconds before Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy. Together, this dynamic pair began a journey through space aided by a galaxyful of fellow travelers.",
  "pageCount": 224,
  "authors": "Douglas Adams",
  "tags": ["Science Fiction", "Humor", "Adventure"],
  "price": "159.99",
  "averageRating": 4.6,
  "ratingsCount": 14532,
  "trending":true,
    "bestSelling":true
  },
  {
    "id": 31,
    "title": "Thinking, Fast and Slow",
    "category": "Educational",
    "coverImage": "http://books.google.com/books/content?id=ZuKTvERuPG8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "In this work the author, a recipient of the Nobel Prize in Economic Sciences, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical.",
    "pageCount": 499,
    "authors": "Daniel Kahneman",
    "tags": ["Educational", "Psychology", "Non-fiction"],
    "price": "229.99",
    "averageRating": 4.5,
    "ratingsCount": 9876
  },
  {
    "id": 32,
    "title": "Educated",
    "category": "Educational",
    "coverImage": "http://books.google.com/books/content?id=2ObWDgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Tara Westover was seventeen the first time she set foot in a classroom. Born to survivalists in the mountains of Idaho, she prepared for the end of the world by stockpiling home-canned peaches. An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    "pageCount": 334,
    "authors": "Tara Westover",
    "tags": ["Educational", "Biography", "Memoir"],
    "price": "199.99",
    "averageRating": 4.6,
    "ratingsCount": 11234
  },
  {
    "id": 33,
    "title": "How to Read a Book",
    "category": "Educational",
    "coverImage": "http://books.google.com/books/content?id=Z5PpkQadm5EC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "With half a million copies in print, How to Read a Book is the best and most successful guide to reading comprehension for the general reader, completely rewritten and updated with new material.",
    "pageCount": 426,
    "authors": "Mortimer J. Adler, Charles Van Doren",
    "tags": ["Educational", "Self-Help", "Learning"],
    "price": "179.99",
    "averageRating": 4.3,
    "ratingsCount": 5432
  },
  {
    "id": 34,
    "title": "Atomic Habits",
    "category": "Educational",
    "coverImage": "http://books.google.com/books/content?id=XfFvDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    "pageCount": 320,
    "authors": "James Clear",
    "tags": ["Educational", "Self-Help", "Productivity"],
    "price": "189.99",
    "averageRating": 4.7,
    "ratingsCount": 18765,
    "trending":true,
  },
  {
    "id": 35,
    "title": "Make It Stick",
    "category": "Educational",
    "coverImage": "http://books.google.com/books/content?id=fpAXEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "To most of us, learning something 'the hard way' implies wasted time and effort. Good teaching, we believe, should be creatively tailored to the different learning styles of students and should use strategies that make learning easier. Make It Stick turns fashionable ideas like these on their head.",
    "pageCount": 336,
    "authors": "Peter C. Brown, Henry L. Roediger III, Mark A. McDaniel",
    "tags": ["Educational", "Learning", "Psychology"],
    "price": "169.99",
    "averageRating": 4.4,
    "ratingsCount": 6234
  },
  {
    "id": 36,
    "title": "The Elements of Style",
    "category": "Academic",
    "coverImage": "http://books.google.com/books/content?id=46DMDAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "This classic book is a must-have for anyone who cares about writing. The Elements of Style is a prescriptive American English writing style guide comprising eight 'elementary rules of usage', ten 'elementary principles of composition', and more.",
    "pageCount": 105,
    "authors": "William Strunk Jr., E.B. White",
    "tags": ["Academic", "Writing", "Reference"],
    "price": "99.99",
    "averageRating": 4.5,
    "ratingsCount": 7654
  },
  {
    "id": 37,
    "title": "The Republic",
    "category": "Academic",
    "coverImage": "http://books.google.com/books/content?id=I7lhPhT3K2sC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Plato's most famous work and one of the most important books ever written on the subject of philosophy and political theory, The Republic is a Socratic dialogue on justice in the soul and in the state.",
    "pageCount": 416,
    "authors": "Plato",
    "tags": ["Academic", "Philosophy", "Classics"],
    "price": "149.99",
    "averageRating": 4.2,
    "ratingsCount": 5432
  },
  {
    "id": 38,
    "title": "A Brief History of Time",
    "category": "Academic",
    "coverImage": "http://books.google.com/books/content?id=1Q6nDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "A landmark volume in science writing by one of the great minds of our time, Stephen Hawking's book explores fundamental questions about the universe. From the Big Bang to black holes, this is a brilliantly accessible exploration of physics.",
    "pageCount": 212,
    "authors": "Stephen Hawking",
    "tags": ["Academic", "Physics", "Science"],
    "price": "189.99",
    "averageRating": 4.3,
    "ratingsCount": 9876
  },
  {
    "id": 39,
    "title": "The Wealth of Nations",
    "category": "Academic",
    "coverImage": "http://books.google.com/books/content?id=j8UaAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Adam Smith's masterpiece, first published in 1776, is the foundation of modern economic thought and remains the single most important account of the rise of, and the principles behind, modern capitalism.",
    "pageCount": 1152,
    "authors": "Adam Smith",
    "tags": ["Academic", "Economics", "Philosophy"],
    "price": "249.99",
    "averageRating": 4.1,
    "ratingsCount": 4321
  },
  {
    "id": 40,
    "title": "Introduction to Algorithms",
    "category": "Academic",
    "coverImage": "http://books.google.com/books/content?id=NLngYyWFl_YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "description": "Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. The book covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers.",
    "pageCount": 1312,
    "authors": "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    "tags": ["Academic", "Computer Science", "Textbook"],
    "price": "299.99",
    "averageRating": 4.4,
    "ratingsCount": 6789
  }
];
